"""
Improvement Service
===================
Enhances original content by embedding missing entities based on recommendations.
Designed to be LLM-agnostic so it can be seamlessly swapped with robust models 
in the future.
"""

from typing import Any, Dict, List

def improve_content(original_content: str, recommendations: List[Dict[str, Any]]) -> str:
    """
    Improves content by adding sentences that cover missing high-priority entities.
    
    Currently uses rule-based additions but ensures the interface is ready for 
    LLM integration in a future phase.
    
    Args:
        original_content: The original generated or provided text.
        recommendations: List of recommendation dicts generated by the 
                         recommendation service.
                         
    Returns:
        The improved content string.
    """
    
    # TODO for Phase n: Replace mock below with actual LLM API call.
    # entities_to_add = [r['entity'] for r in recommendations[:5]]
    # prompt = f"Improve this content by naturally integrating these missing concepts: {entities_to_add}\n\nContent:\n{original_content}"
    # response = llm_client.generate(prompt)
    # return response.text
    
    if not recommendations:
        return original_content
        
    improved_content = original_content.strip()
    
    # Prepare improvement additions
    additions = []
    seen_entities = set()
    
    # Focus on top recommendations (limit to top 5 for readability)
    top_recs = recommendations[:5]
    
    for rec in top_recs:
        entity = rec.get("entity")
        if not entity or entity.lower() in seen_entities:
            continue
            
        seen_entities.add(entity.lower())
        
        # Simple rule-based sentence generation
        category = rec.get("category", "the industry").replace("_", " ")
        sentence = f"Additionally, {entity} plays a key role in the context of {category}."
        additions.append(sentence)
        
    # Append the new sentences cleanly
    if additions:
        joined_additions = " ".join(additions)
        improved_content = f"{improved_content}\n\nAdditional Insights:\n{joined_additions}"
        
    return improved_content
